---
# tasks file for roles/osp-instance-delete
   - name: Fetch Instance Info
     os_server_info:
      cloud: openstack
     register: result

  - name: Delete instances
     os_server:
      name: "{{ item.name }}"
      state: absent
      # ansible_ssh_private_key_file: ~/.ssh/openstack.pem
      # ansible_ssh_user: cloud-user
     with_items: "{{result.openstack_servers}}"