---
- name: Install "{{ payload }}"
  package:
    name: "{{ payload }}"
    state: present

- name: Enable "{{ payload }}"    
  service:
    name: "{{ payload }}"
    enabled: yes

- name: Copy haproxy config
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644

- name: Start "{{ payload }}"
  service:
    name: "{{ payload  }}"
    state: started

...


