---
- name: Install "{{ payload }}"
  package:
    name: "{{ payload }}"
    state: present

- name: Copy jar file into tomcat bin
  copy:
    src: /usr/share/java/tomcat/extras/tomcat-juli.jar
    dest: /usr/share/tomcat/bin/tomcat-juli.jar
    remote_src: yes

- name: Enable "{{ payload }}" 
  service:
    name: "{{ payload }}"
    enabled: yes

- name: Create Tomcat content directory
  file:
    path: "{{ tomcat_web_root }}"
    state: directory

- name: Copy static index.html to tomcat webapps/ansible/index.html
  template:
    src: templates/index.html.j2
    dest: {{ tomcat_web_root }}/index.html
    mode: 0644

- name: Start "{{ payload }}"
  service:
    name: "{{ payload  }}"
    state: started

...

